# Generated by Django 2.2.13 on 2022-07-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=200)),
                ('Duration', models.DurationField()),
                ('venue', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('creation_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
            ],
        ),
        migrations.RemoveField(
            model_name='policyrecord',
            name='Policy',
        ),
        migrations.RemoveField(
            model_name='policyrecord',
            name='candidate',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.DeleteModel(
            name='PolicyRecord',
        ),
        migrations.AddField(
            model_name='conference',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.Category'),
        ),
    ]
