# Generated by Django 2.2.13 on 2022-07-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20220716_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='paper/Candidate/'),
        ),
    ]
