# Generated by Django 2.2.13 on 2022-07-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_remove_conference_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='paper/Candidate/'),
        ),
    ]
