# Generated by Django 2.2.13 on 2022-07-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='paper/Candidate/'),
        ),
    ]
