# Generated by Django 2.2.13 on 2022-07-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20220712_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='Date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Duration',
            field=models.PositiveIntegerField(),
        ),
    ]
