# Generated by Django 2.2.13 on 2022-07-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='media/paper/Candidate/'),
        ),
    ]
