# Generated by Django 2.2.13 on 2022-07-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20220719_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='paper/Candidate/'),
        ),
    ]
