# Generated by Django 2.2.13 on 2022-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20220720_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.FileField(blank=True, null=True, upload_to='paper/Candidate/')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='paper',
        ),
    ]
