# Generated by Django 2.2.13 on 2022-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20220720_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/Candidate/'),
        ),
    ]
