# Generated by Django 2.2.13 on 2022-07-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20220720_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paper',
        ),
        migrations.AddField(
            model_name='candidate',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='paper/Candidate/'),
        ),
    ]
